"use strict";
var assert = require("assert");
var fs = require("fs");
var path = require("path");
var root = path.join(__dirname, "..");
var dialog = fs.readFileSync(path.join(root, "public/shared/ui/parameter-dialog.js"), "utf8");
var automation = fs.readFileSync(path.join(root, "server/modules/automation/index.js"), "utf8");
var client = fs.readFileSync(path.join(root, "public/modules/automation/index.js"), "utf8");
var css = fs.readFileSync(path.join(root, "public/shared/ui/shared-ui.css"), "utf8");
assert.ok(dialog.indexOf('value: "none", label: "Bez zmian"') >= 0 && dialog.indexOf('value: "receive", label: "Przyjęcie sprzętu"') >= 0 && dialog.indexOf('value: "return", label: "Zdanie sprzętu"') >= 0);
assert.ok(dialog.indexOf('values.JiraAssetActionsJson = JSON.stringify(map);') >= 0);
assert.ok(dialog.indexOf('text(variable && variable.name) === "IsTransferProtocol"') >= 0, "Legacy global mode must be hidden for the protocol runtime.");
assert.ok(dialog.indexOf('record.optionHost.addEventListener("change", onChecklistChanged)') >= 0 && dialog.indexOf('select.addEventListener(') < 0, "Action rows must reuse the delegated checklist handler.");
assert.ok(dialog.indexOf("disabledActions") >= 0);
assert.ok(css.indexOf(".mc-parameter-checklist-item-actions") >= 0 && css.indexOf(".mc-parameter-checklist-action-select") >= 0);
assert.ok(automation.indexOf('jira-protocol-v2-service.js') >= 0 && automation.indexOf("requiresRequesterConfirmation") >= 0 && automation.indexOf("confirmRequester") >= 0);
assert.ok(automation.indexOf("_jiraConfirmation") >= 0, "Private mutation snapshot must be stripped before browser presentation.");
assert.ok(client.indexOf('"awaiting_confirmation"') >= 0);
console.log("Jira per-asset action UI uses shared checklist ownership and no visible global mode: OK");
