from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'marker not found in {path}: {old[:100]!r}')
    text = text.replace(old, new, 1)
    p.write_text(text, encoding='utf-8')

# #249: remove the obsolete top-level Permissions tab.
replace_once(
    'views/SIRK-Portal.handlebars',
    '            <button type="button" data-tab="myscripts">My Scripts</button>\n            <button type="button" data-tab="permissions">Permissions</button>\n',
    '            <button type="button" data-tab="myscripts">My Scripts</button>\n'
)

# #249: allow modulePermissions to reuse the same renderer with a local subsection title.
replace_once(
    'web/admin/admin.js',
    '    function modulePermissions(host, title, source, folders) {\n',
    '    function modulePermissions(host, title, source, folders, sectionTitle) {\n'
)
replace_once(
    'web/admin/admin.js',
    '        var card = disclosure(host, "mc-admin-provider-card mc-admin-permission-module", title, false);\n',
    '        var card = disclosure(host, "mc-admin-provider-card mc-admin-permission-module", sectionTitle || title, false);\n'
)

# #248: one browser owner for target-mesh approval level controls.
insert_marker = '    function save(values, status, button) {\n'
admin = Path('web/admin/admin.js')
text = admin.read_text(encoding='utf-8')
if 'function moveRequestApprovalLevels(' not in text:
    helper = '''    function moveRequestApprovalLevels(host, snapshot) {\n        snapshot = snapshot || {};\n        var meshes = Array.isArray(snapshot.meshes) ? snapshot.meshes : [];\n        var settingsValue = snapshot.settings || {};\n        var configured = settingsValue.targetMeshApprovalLevels && typeof settingsValue.targetMeshApprovalLevels === "object"\n            ? settingsValue.targetMeshApprovalLevels\n            : {};\n        var section = disclosure(host, "mc-admin-provider-card mc-admin-move-policy", "Approval levels by target device group", false);\n        section.appendChild(element("p", "mc-admin-card-description", "Select the approval levels required when moving a device into each target group. No selected levels means immediate execution without approval."));\n        var readers = [];\n        meshes.forEach(function (mesh) {\n            var meshId = String(mesh && mesh.id || "");\n            if (!meshId) return;\n            var explicit = Object.prototype.hasOwnProperty.call(configured, meshId);\n            var levels = explicit && Array.isArray(configured[meshId]) ? configured[meshId].map(Number) : [1];\n            var row = element("fieldset", "mc-admin-move-policy-row");\n            row.appendChild(element("legend", "mc-admin-field-label", String(mesh.name || meshId)));\n            var inputs = [1, 2, 3].map(function (level) {\n                var label = element("label", "mc-admin-check");\n                var input = document.createElement("input");\n                input.type = "checkbox";\n                input.checked = levels.indexOf(level) >= 0;\n                label.appendChild(input);\n                label.appendChild(document.createTextNode("Level " + level));\n                row.appendChild(label);\n                return { level: level, input: input };\n            });\n            section.appendChild(row);\n            readers.push({\n                id: meshId,\n                read: function () {\n                    return inputs.filter(function (entry) { return entry.input.checked; }).map(function (entry) { return entry.level; });\n                }\n            });\n        });\n        if (!readers.length) section.appendChild(element("div", "mc-admin-notice", "No MeshCentral device groups are available."));\n        return function () {\n            var result = {};\n            readers.forEach(function (entry) { result[entry.id] = entry.read(); });\n            return result;\n        };\n    }\n\n'''
    if insert_marker not in text:
        raise SystemExit('admin save marker missing')
    text = text.replace(insert_marker, helper + insert_marker, 1)
    admin.write_text(text, encoding='utf-8')

# #249 + #248 render/save paths.
old_render = '''        } else if (tab === "moverequests") {\n            card.appendChild(element("h3", "", "Move Request"));\n            var enabled = checked(card, "Enable Move Requests", moduleEnabled("moverequests"));\n            var hostButton = checked(card, "Show the Move Request button on device pages", !(current.moverequests && current.moverequests.hostButtonEnabled === false));\n            actions(card, function () {\n                return { modules: { moverequests: enabled.checked }, moduleOptions: { moverequests: { hostButtonEnabled: hostButton.checked } } };\n            });\n        } else if (tab === "mycommands") {\n            card.appendChild(element("h3", "", "My Commands"));\n            var commandEnabled = checked(card, "Enable My Commands", moduleEnabled("mycommands"));\n            var desktop = checked(card, "Show Commands in Desktop", !(current.mycommands && current.mycommands.showOnDevice === false));\n            actions(card, function () {\n                return { modules: { mycommands: commandEnabled.checked }, moduleOptions: { mycommands: { showOnDevice: desktop.checked } } };\n            });\n        } else if (tab === "permissions") {\n            card.appendChild(element("h3", "", "Permissions"));\n            card.appendChild(element("p", "mc-admin-card-description", "Grant script and command execution through MeshCentral user groups. Add a user to one of the selected groups to give access."));\n            var folderData = data.folderPermissions || {};\n            var commandPermissions = modulePermissions(card, "My Commands", current.mycommands, folderData.mycommands);\n            var scriptPermissions = modulePermissions(card, "My Scripts", current.myscripts, folderData.myscripts);\n            actions(card, function () {\n                return {\n                    modules: {},\n                    moduleOptions: {\n                        permissions: {\n                            mycommands: commandPermissions(),\n                            myscripts: scriptPermissions()\n                        }\n                    }\n                };\n            });\n        } else {\n            card.appendChild(element("h3", "", "My Scripts"));\n            var scriptEnabled = checked(card, "Enable My Scripts", moduleEnabled("myscripts"));\n            actions(card, function () { return { modules: { myscripts: scriptEnabled.checked }, moduleOptions: {} }; });\n        }\n'''
new_render = '''        } else if (tab === "moverequests") {\n            card.appendChild(element("h3", "", "Move Request"));\n            var enabled = checked(card, "Enable Move Requests", moduleEnabled("moverequests"));\n            var hostButton = checked(card, "Show the Move Request button on device pages", !(current.moverequests && current.moverequests.hostButtonEnabled === false));\n            var moveApprovalLevels = moveRequestApprovalLevels(card, data.moveRequestAdmin);\n            actions(card, function () {\n                return {\n                    modules: { moverequests: enabled.checked },\n                    moduleOptions: { moverequests: {\n                        hostButtonEnabled: hostButton.checked,\n                        targetMeshApprovalLevels: moveApprovalLevels()\n                    } }\n                };\n            });\n        } else if (tab === "mycommands") {\n            card.appendChild(element("h3", "", "My Commands"));\n            var commandEnabled = checked(card, "Enable My Commands", moduleEnabled("mycommands"));\n            var desktop = checked(card, "Show Commands in Desktop", !(current.mycommands && current.mycommands.showOnDevice === false));\n            var folderData = data.folderPermissions || {};\n            var commandPermissions = modulePermissions(card, "My Commands", current.mycommands, folderData.mycommands, "Permissions");\n            actions(card, function () {\n                return {\n                    modules: { mycommands: commandEnabled.checked },\n                    moduleOptions: {\n                        mycommands: { showOnDevice: desktop.checked },\n                        permissions: { mycommands: commandPermissions() }\n                    }\n                };\n            });\n        } else {\n            card.appendChild(element("h3", "", "My Scripts"));\n            var scriptEnabled = checked(card, "Enable My Scripts", moduleEnabled("myscripts"));\n            var scriptFolderData = data.folderPermissions || {};\n            var scriptPermissions = modulePermissions(card, "My Scripts", current.myscripts, scriptFolderData.myscripts, "Permissions");\n            actions(card, function () {\n                return {\n                    modules: { myscripts: scriptEnabled.checked },\n                    moduleOptions: { permissions: { myscripts: scriptPermissions() } }\n                };\n            });\n        }\n'''
replace_once('web/admin/admin.js', old_render, new_render)

# #123: keep one observer but reconcile live host surface and replaced Modern stylesheet.
old_observer = '''    function observeHostTheme() {\n        syncHostTheme();\n        if (typeof hostWindow.MutationObserver === "function") {\n            var observer = new hostWindow.MutationObserver(syncHostTheme);\n            if (hostDocument && hostDocument.documentElement) {\n                observer.observe(hostDocument.documentElement, { attributes: true, attributeFilter: ["class", "data-bs-theme"] });\n            }\n            if (hostDocument && hostDocument.body && hostDocument.body !== hostDocument.documentElement) {\n                observer.observe(hostDocument.body, { attributes: true, attributeFilter: ["class", "data-bs-theme"] });\n            }\n            var themeStylesheet = hostDocument && hostDocument.getElementById ? hostDocument.getElementById("theme-stylesheet") : null;\n            if (themeStylesheet) {\n                observer.observe(themeStylesheet, { attributes: true, attributeFilter: ["href"] });\n                if (typeof themeStylesheet.addEventListener === "function") themeStylesheet.addEventListener("load", syncHostTheme);\n            }\n        }\n        if (hostWindow.matchMedia) {\n'''
new_observer = '''    function observeHostTheme() {\n        syncHostTheme();\n        if (typeof hostWindow.MutationObserver === "function") {\n            var observedStylesheet = null;\n            var observedSurface = null;\n            var observer;\n            function bindLiveThemeOwners() {\n                var themeStylesheet = hostDocument && hostDocument.getElementById ? hostDocument.getElementById("theme-stylesheet") : null;\n                if (themeStylesheet !== observedStylesheet) {\n                    if (observedStylesheet && typeof observedStylesheet.removeEventListener === "function") observedStylesheet.removeEventListener("load", syncHostTheme);\n                    observedStylesheet = themeStylesheet;\n                    if (observedStylesheet) {\n                        observer.observe(observedStylesheet, { attributes: true, attributeFilter: ["href"] });\n                        if (typeof observedStylesheet.addEventListener === "function") observedStylesheet.addEventListener("load", syncHostTheme);\n                    }\n                }\n                var surface = hostSurfaceStyle();\n                var surfaceElement = surface && surface.element;\n                if (surfaceElement && surfaceElement !== hostDocument.body && surfaceElement !== hostDocument.documentElement && surfaceElement !== observedSurface) {\n                    observedSurface = surfaceElement;\n                    observer.observe(observedSurface, { attributes: true, attributeFilter: ["class", "style"] });\n                }\n            }\n            observer = new hostWindow.MutationObserver(function () {\n                bindLiveThemeOwners();\n                syncHostTheme();\n            });\n            if (hostDocument && hostDocument.documentElement) {\n                observer.observe(hostDocument.documentElement, { attributes: true, attributeFilter: ["class", "data-bs-theme"] });\n            }\n            if (hostDocument && hostDocument.body && hostDocument.body !== hostDocument.documentElement) {\n                observer.observe(hostDocument.body, { attributes: true, attributeFilter: ["class", "data-bs-theme"] });\n            }\n            if (hostDocument && hostDocument.head) {\n                observer.observe(hostDocument.head, { childList: true });\n            }\n            bindLiveThemeOwners();\n        }\n        if (hostWindow.matchMedia) {\n'''
replace_once('web/admin/admin.js', old_observer, new_observer)

# #248 backend owner: expose canonical normalizer/admin snapshot without duplicating validation.
mr = Path('server/modules/move-requests/index.js')
text = mr.read_text(encoding='utf-8')
marker = '    function configuredLevels(targetMeshId) {\n'
if 'function normalizeAdminSettings(' not in text:
    helper = '''    function normalizeAdminSettings(value, user) {\n        value = value && typeof value === "object" && !Array.isArray(value) ? value : {};\n        var allowedMeshes = meshRows(user).map(function (mesh) { return mesh.id; });\n        var result = { hostButtonEnabled: value.hostButtonEnabled !== false };\n        if (Object.prototype.hasOwnProperty.call(value, "targetMeshApprovalLevels")) {\n            result.targetMeshApprovalLevels = normalizeMeshApprovalLevels(value.targetMeshApprovalLevels, allowedMeshes);\n        }\n        return result;\n    }\n\n    function getAdminSettings(user) {\n        if (!shared.isSiteAdmin(user)) throw new Error("Permission denied.");\n        return {\n            settings: shared.copy(context.settings.read().modules.moverequests || {}),\n            meshes: meshRows(user)\n        };\n    }\n\n'''
    if marker not in text:
        raise SystemExit('move requests marker missing')
    text = text.replace(marker, helper + marker, 1)
text = text.replace(
'''            if (asset === "settings") {\n                if (!shared.isSiteAdmin(user)) throw new Error("Permission denied.");\n                var current = context.settings.read().modules.moverequests || {};\n                return {\n                    ok: true,\n                    settings: current,\n                    meshes: meshRows(user)\n                };\n            }\n''',
'''            if (asset === "settings") {\n                var adminSettings = getAdminSettings(user);\n                adminSettings.ok = true;\n                return adminSettings;\n            }\n''', 1)
text = text.replace(
'''            if (asset === "settings") {\n                if (!shared.isSiteAdmin(user)) throw new Error("Permission denied.");\n                var allowedMeshes = meshRows(user).map(function (mesh) { return mesh.id; });\n                return context.settings.update(function (current) {\n                    current.modules.moverequests.hostButtonEnabled = value.hostButtonEnabled !== false;\n                    current.modules.moverequests.menuEnabled = false;\n                    if (Object.prototype.hasOwnProperty.call(value, "targetMeshApprovalLevels")) {\n                        current.modules.moverequests.targetMeshApprovalLevels = normalizeMeshApprovalLevels(\n                            value.targetMeshApprovalLevels,\n                            allowedMeshes\n                        );\n                    }\n                    return current;\n                }).then(function () { return { ok: true }; });\n            }\n''',
'''            if (asset === "settings") {\n                if (!shared.isSiteAdmin(user)) throw new Error("Permission denied.");\n                var normalized = normalizeAdminSettings(value, user);\n                return context.settings.update(function (current) {\n                    current.modules.moverequests.hostButtonEnabled = normalized.hostButtonEnabled;\n                    current.modules.moverequests.menuEnabled = false;\n                    if (Object.prototype.hasOwnProperty.call(normalized, "targetMeshApprovalLevels")) {\n                        current.modules.moverequests.targetMeshApprovalLevels = normalized.targetMeshApprovalLevels;\n                    }\n                    return current;\n                }).then(function () { return { ok: true }; });\n            }\n''', 1)
return_marker = '        getAccess: access,\n'
if 'getAdminSettings: getAdminSettings' not in text:
    text = text.replace(return_marker, '        getAccess: access,\n        getAdminSettings: getAdminSettings,\n        normalizeAdminSettings: normalizeAdminSettings,\n', 1)
mr.write_text(text, encoding='utf-8')

# #248 central Admin one-save integration.
runtime = Path('server/core/runtime.js')
text = runtime.read_text(encoding='utf-8')
text = text.replace(
'''                if (moduleOptions.moverequests) {\n                    current.modules.moverequests.hostButtonEnabled = moduleOptions.moverequests.hostButtonEnabled !== false;\n                }\n''',
'''                if (moduleOptions.moverequests) {\n                    var moveOptions = modules.moverequests && typeof modules.moverequests.normalizeAdminSettings === "function"\n                        ? modules.moverequests.normalizeAdminSettings(moduleOptions.moverequests, user)\n                        : { hostButtonEnabled: moduleOptions.moverequests.hostButtonEnabled !== false };\n                    current.modules.moverequests.hostButtonEnabled = moveOptions.hostButtonEnabled !== false;\n                    if (Object.prototype.hasOwnProperty.call(moveOptions, "targetMeshApprovalLevels")) {\n                        current.modules.moverequests.targetMeshApprovalLevels = moveOptions.targetMeshApprovalLevels;\n                    }\n                }\n''', 1)
text = text.replace(
'''            uiSettings: shared.copy(current.ui || { iconMode: "auto" }),\n            folderPermissions: {\n''',
'''            uiSettings: shared.copy(current.ui || { iconMode: "auto" }),\n            moveRequestAdmin: modules.moverequests && !modules.moverequests.__loadError && typeof modules.moverequests.getAdminSettings === "function"\n                ? modules.moverequests.getAdminSettings(user)\n                : null,\n            folderPermissions: {\n''', 1)
runtime.write_text(text, encoding='utf-8')

# Update stale tests and add focused contracts.
Path('test/admin-permissions-ui.test.js').write_text('''"use strict";\n\nvar assert = require("assert");\nvar fs = require("fs");\nvar path = require("path");\n\nvar root = path.resolve(__dirname, "..");\nvar view = fs.readFileSync(path.join(root, "views", "SIRK-Portal.handlebars"), "utf8");\nvar browser = fs.readFileSync(path.join(root, "web", "admin", "admin.js"), "utf8");\nvar runtime = fs.readFileSync(path.join(root, "server", "core", "runtime.js"), "utf8");\n\nassert.ok(view.indexOf('data-tab="permissions"') < 0, "Top-level Permissions tab must be removed.");\nassert.ok(browser.indexOf('tab === "permissions"') < 0, "Administration browser must not keep a second Permissions page owner.");\nassert.ok(browser.indexOf('modulePermissions(card, "My Commands", current.mycommands, folderData.mycommands, "Permissions")') >= 0, "My Commands must render its existing permission owner locally.");\nassert.ok(browser.indexOf('modulePermissions(card, "My Scripts", current.myscripts, scriptFolderData.myscripts, "Permissions")') >= 0, "My Scripts must render its existing permission owner locally.");\nassert.ok(browser.indexOf("Restrict module access to selected MeshCentral user groups") >= 0);\nassert.ok(browser.indexOf("Allow every user who has module access") >= 0);\nassert.ok(runtime.indexOf("moduleOptions.permissions") >= 0);\nassert.ok(runtime.indexOf("folderAccess.normalizeRules") >= 0);\nconsole.log("Admin module-local permissions UI contract: OK");\n''', encoding='utf-8')

Path('test/admin-move-request-policy-ui.test.js').write_text('''"use strict";\nvar assert = require("assert");\nvar fs = require("fs");\nvar path = require("path");\nvar root = path.resolve(__dirname, "..");\nvar browser = fs.readFileSync(path.join(root, "web", "admin", "admin.js"), "utf8");\nvar runtime = fs.readFileSync(path.join(root, "server", "core", "runtime.js"), "utf8");\nvar moduleSource = fs.readFileSync(path.join(root, "server", "modules", "move-requests", "index.js"), "utf8");\nassert.ok(browser.indexOf("Approval levels by target device group") >= 0);\nassert.ok(browser.indexOf("targetMeshApprovalLevels: moveApprovalLevels()") >= 0);\nassert.ok(browser.indexOf("var levels = explicit && Array.isArray(configured[meshId]) ? configured[meshId].map(Number) : [1]") >= 0, "Missing mesh policy must display effective Level 1 default.");\nassert.ok(runtime.indexOf("moveRequestAdmin:") >= 0, "Admin snapshot must include Move Request settings and meshes in one load.");\nassert.ok(runtime.indexOf("modules.moverequests.normalizeAdminSettings") >= 0, "Central save must reuse Move Requests normalization owner.");\nassert.ok(moduleSource.indexOf("function normalizeAdminSettings(value, user)") >= 0);\nassert.ok(moduleSource.indexOf("normalizeMeshApprovalLevels(value.targetMeshApprovalLevels, allowedMeshes)") >= 0);\nassert.ok(moduleSource.indexOf("getAdminSettings: getAdminSettings") >= 0);\nconsole.log("Admin Move Request per-target approval policy contract: OK");\n''', encoding='utf-8')

Path('test/admin-permissions-placement.test.js').write_text('''"use strict";\nvar assert = require("assert");\nvar fs = require("fs");\nvar path = require("path");\nvar root = path.resolve(__dirname, "..");\nvar browser = fs.readFileSync(path.join(root, "web", "admin", "admin.js"), "utf8");\nvar commandPayload = browser.slice(browser.indexOf('} else if (tab === "mycommands")'), browser.indexOf('} else {', browser.indexOf('} else if (tab === "mycommands")')));\nvar scriptPayload = browser.slice(browser.indexOf('} else {', browser.indexOf('} else if (tab === "mycommands")'), browser.indexOf('    function activate'));\nassert.ok(commandPayload.indexOf("permissions: { mycommands: commandPermissions() }") >= 0);\nassert.ok(commandPayload.indexOf("myscripts: scriptPermissions") < 0, "Commands save must not serialize Scripts permissions.");\nassert.ok(scriptPayload.indexOf("permissions: { myscripts: scriptPermissions() }") >= 0);\nassert.ok(scriptPayload.indexOf("mycommands: commandPermissions") < 0, "Scripts save must not serialize Commands permissions.");\nconsole.log("Admin permissions placement/partial-save browser contract: OK");\n''', encoding='utf-8')

# Strengthen live-theme signal contract: one observer also follows host surface + stylesheet replacement.
theme_test = Path('test/admin-host-theme-signal.test.js')
tt = theme_test.read_text(encoding='utf-8')
if 'hostDocument.head' not in tt:
    tt += '''\nassert.ok(admin.indexOf('observer.observe(hostDocument.head, { childList: true })') >= 0,\n    "Admin theme owner must notice replacement of the Modern theme stylesheet without polling.");\nassert.ok(admin.indexOf('observer.observe(observedSurface, { attributes: true, attributeFilter: ["class", "style"] })') >= 0,\n    "Admin theme owner must follow live mutations on the effective page-43 surface.");\nassert.ok(admin.indexOf('bindLiveThemeOwners();') >= 0,\n    "The existing single observer must rebind current host theme owners before synchronization.");\n'''
    theme_test.write_text(tt, encoding='utf-8')

print('dev42 admin patch applied')
